<a href="https://colab.research.google.com/github/Koushikvarma2003/FML/blob/main/fml_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=np.array([1,4,2,6])
print(type(a),a.shape,a[2])

<class 'numpy.ndarray'> (4,) 2


In [ ]:
a=np.random.random((5,2))
print(a)

[[0.03571545 0.01213209]
 [0.64596993 0.38530326]
 [0.5213538  0.34738485]
 [0.49479885 0.33314243]
 [0.6499875  0.34331202]]


In [ ]:
print(np.__version__)

1.22.4


In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a[:2,1:2]
print(b)

[[2]
 [6]]


In [ ]:
print(a[0,1])
b[0,0]==77
print(a[0,1])


2
2


In [ ]:
row_r1 = a[1, :]      
row_r2 = a[1:2, :]  
row_r3 = a[[1], :]  
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [ ]:
a=np.array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [10,11,12,13]])
print(a[:-1])

[list([0, 1, 2, 3, 4]) list([5, 6, 7, 8, 9])]


<ipython-input-29-54900adcab2f>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a=np.array([[0, 1, 2, 3, 4],
